### ISSUE TITLE
skills are overflowing off the page

### ISSUE THREAD

**Issue by rinorzk** [saadq/resumake.io#208] opened 2023-04-15 10:21 UTC
<img width="840" alt="Screen Shot 2023-04-15 at 12 20 05" src="https://user-images.githubusercontent.com/59566267/232208149-aec1fe56-a991-45b7-a5d4-b018317d0124.png">

Anyone that can help me with this, willing to implement a fix, if someone can guide me a bit.

**Comment by rinorzk** [comment] 2023-04-15 10:25
@saadq any update on this?

**Comment by ducaale** [comment] 2023-04-15 15:37
@rinorzk this appears to be a duplicate of https://github.com/saadq/resumake.io/issues/194 which contains a workaround. Shall we close this and continue the conversation on the mentioned issue?

**Closed** 2023-04-15 23:37 UTC
