### ISSUE TITLE
Feature: To add new sections

### ISSUE THREAD

**Issue by alinawaztechnosoft** [saadq/resumake.io#173] opened 2021-09-16 09:39 UTC
Please add a feature to insert new sections e.g like experience, school etc. If someone wants to add a summary section

**Comment by saadq** [comment] 2021-09-17 02:07
Hi @alinawaztechnosoft in v3 I am planning on adding more default sections as well as allowing users to create custom sections. Closing this for now as a duplicate of #97

**Closed by saadq** 2021-09-17 02:07 UTC

**Comment by astromanish** [comment] 2021-09-27 17:35
@saadq when v3 is releasing?

**Comment by saadq** [comment] 2021-09-28 18:09
Hi @astromanish, you can track the V3 issue here: https://github.com/saadq/resumake.io/issues/63 I'll be posting any major updates there.

The short answer is that it will be released when it's done – it's just something I'm working on slowly in my free time and whenever things get hectic at work I end up taking long breaks away from this project. So there's no release date or anything like that, I would guess somewhere around 1-4 months.

**Comment by astromanish** [comment] 2021-09-28 21:48
@saadq Okay! Thanks a lot
